In [1]:
"""
@Name : Subodh Dharmadhikari
@PRN : 18030142043
@MSc CA (Data Science)
"""
import numpy as nump

def softmaxFunc(arr):
    arr = arr if type(arr) is nump.ndarray else nump.array(arr)
    softmax_val = list()
    for x in nump.nditer(arr,flags=['external_loop'],order='F'):
        softmax_val.append([j/sum([nump.exp(i) for i in x]) for j in [nump.exp(i) for i in x]])
    return nump.array(softmax_val)

print("\n\nSoftMax Function using 1D Array:")
arr1d = nump.array([10,20,30])
print("SoftMax Result for arr1d:")
print(softmaxFunc(arr1d))

print("\n\nSoftMax Function using 2D Array:")
arr2d = nump.array([[10,20,30],[40,50,60],[10,101,100]])
print("Given Array, arr2d:",arr2d)
print(softmaxFunc(arr2d))

print("\n\nSoftMax Function using 3D Array:")
arr3d = nump.array([[[10,20,30]],[[40,50,60]],[[70,80,90]]])
print("SoftMax Result for arr3d:")

print(softmaxFunc(arr3d))




SoftMax Function using 1D Array:
SoftMax Result for arr1d:
[[2.06106005e-09 4.53978686e-05 9.99954600e-01]]


SoftMax Function using 2D Array:
Given Array, arr2d: [[ 10  20  30]
 [ 40  50  60]
 [ 10 101 100]]
[[9.35762297e-14 1.00000000e+00 9.35762297e-14]
 [6.63967720e-36 7.09547416e-23 1.00000000e+00]
 [3.97544974e-31 4.24835426e-18 1.00000000e+00]]


SoftMax Function using 3D Array:
SoftMax Result for arr3d:
[[8.75651076e-27 9.35762297e-14 1.00000000e+00]
 [8.75651076e-27 9.35762297e-14 1.00000000e+00]
 [8.75651076e-27 9.35762297e-14 1.00000000e+00]]
